### ISSUE TITLE
fix(net-helper): main does not compile — render_vm_policy deleted while two callers remain

### ISSUE THREAD

**Issue by SteelCrab** [SteelCrab/firecrab#228]
## Summary

- `main` does not compile: `cargo check -p firecrab-net-helper --all-targets` fails with two `error[E0425]: cannot find function 'render_vm_policy' in this scope` at `firecrab-net-helper/src/firewall.rs:1244` and `:1268`
- Cause is a semantic merge conflict between two independently-green PRs, not any single bad commit:
  - `c80c9eb` (2026-08-21, dual-stack) added two tests calling the `render_vm_policy(uplink, policy)` wrapper
  - `57f48d2` (2026-08-26, #192 clippy cleanup) was written on a base predating those tests; it deleted the wrapper and rewrote the 11 call sites it could see
  - `d2d4303` (2026-09-02, merge of #195) combined both cleanly line-by-line, leaving the wrapper deleted and two callers pointing at nothing
- Every open PR's merge build now fails on this, e.g. #227's `Rust (fmt, clippy, test + coverage)` and `Clippy warning regression gate`
- The wrapper was a one-liner — `render_vm_policy(uplink, policy)` == `render_vm_policy_for_network(uplink, policy, true)` — so the two stragglers just need the same rewrite the other 11 already got

## Architecture

```mermaid
flowchart TD
    Dual["c80c9eb 08-21<br/>dual-stack tests call render_vm_policy()"]
    Fork["57f48d2 08-26 (fork, older base)<br/>delete wrapper, rewrite the 11 visible callers"]
    MergeMain["d2d4303 09-02<br/>merge PR #195 into main"]
    Broken["main: wrapper gone,<br/>2 callers still reference it"]
    PRs["every open PR's merge build<br/>fails to compile"]

    Dual --> MergeMain
    Fork --> MergeMain
    MergeMain --> Broken --> PRs
```

## Scope (MVP)

- [ ] Rewrite `firewall.rs:1244` and `:1268` to `render_vm_policy_for_network(uplink, policy, true)`, matching the other 11 call sites
- [ ] `cargo check -p firecrab-net-helper --all-targets` and `cargo test -p firecrab-net-helper` clean on `main`
- [ ] Confirm #227's merge build goes green without touching that branch
- Not in MVP: guarding against this class of cross-PR semantic conflict in CI (e.g. re-running merge builds when `main` moves)
